services:
  -type: web
   runtime: static
   name: rauan-tuken-cv
   rootDir: my_resume_webapp
   buildCommand: npm ci && npm run build
   staticPublishPath: ./out
   pullRequestPreviewsEnabled: false